# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-05-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=50)),
                ('analysis_save', models.CharField(max_length=50, unique=True)),
                ('analysis_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='csv_file',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50, unique=True)),
                ('file_save', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='csv_file',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user_info'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.csv_file'),
        ),
    ]
